[package]
name = "bfc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bfc"
path = "src/bin/bfc.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
clap-verbosity-flag = "3.0.2"
env_logger = "0.11.8"
log = "0.4.27"
thiserror = "2.0.12"
